name: pytorch-practice-cpu
channels:
    - pytorch
    - defaults
dependencies:
    - blas=1.0
    - brotli-python=1.0.9
    - ca-certificates=2024.3.11
    - certifi=2024.2.2
    - charset-normalizer=2.0.4
    - cpuonly=2.0
    - filelock=3.13.1
    - freetype=2.12.1
    - gmpy2=2.1.2
    - idna=3.7
    - intel-openmp=2021.4.0
    - jinja2=3.1.3
    - jpeg=9e
    - lcms2=2.12
    - lerc=3.0
    - libdeflate=1.17
    - libjpeg-turbo=2.0.0
    - libpng=1.6.39
    - libtiff=4.5.1
    - libuv=1.44.2
    - libwebp-base=1.3.2
    - lz4-c=1.9.4
    - markupsafe=2.1.3
    - mkl=2021.4.0
    - mkl-service=2.4.0
    - mkl_fft=1.3.1
    - mkl_random=1.2.2
    - mpc=1.1.0
    - mpfr=4.0.2
    - mpir=3.0.0
    - mpmath=1.3.0
    - networkx=3.1
    - numpy=1.24.3
    - numpy-base=1.24.3
    - openjpeg=2.4.0
    - openssl=3.0.13
    - pillow=10.3.0
    - pip=24.0
    - pysocks=1.7.1
    - python=3.9.19
    - pytorch=2.3.0
    - pytorch-mutex=1.0
    - pyyaml=6.0.1
    - requests=2.31.0
    - setuptools=69.5.1
    - six=1.16.0
    - sqlite=3.45.3
    - sympy=1.12
    - torchaudio=2.3.0
    - torchvision=0.18.0
    - typing_extensions=4.11.0
    - urllib3=2.2.1
    - vc=14.2
    - vs2015_runtime=14.29.30133
    - wheel=0.43.0
    - win_inet_pton=1.1.0
    - xz=5.4.6
    - yaml=0.2.5
    - zlib=1.2.13
    - zstd=1.5.5
    - pip:
          - pandas==2.2.2
          - python-dateutil==2.9.0.post0
          - pytz==2024.1
          - tzdata==2024.1
