name: tensorflow-practice-gpu
channels:
    - conda-forge
    - defaults
dependencies:
    - _tflow_select=2.3.0
    - abseil-cpp=20211102.0
    - absl-py=2.1.0
    - aiohttp=3.9.5
    - aiosignal=1.2.0
    - astunparse=1.6.3
    - async-timeout=4.0.3
    - attrs=23.1.0
    - blas=1.0
    - blinker=1.6.2
    - brotli-python=1.0.9
    - c-ares=1.19.1
    - ca-certificates=2024.3.11
    - cachetools=5.3.3
    - certifi=2024.2.2
    - cffi=1.16.0
    - charset-normalizer=2.0.4
    - click=8.1.7
    - colorama=0.4.6
    - cryptography=41.0.3
    - cudatoolkit=11.2.2
    - cudnn=8.1.0.77
    - flatbuffers=2.0.0
    - frozenlist=1.4.0
    - gast=0.4.0
    - giflib=5.2.1
    - google-auth=2.29.0
    - google-auth-oauthlib=0.4.4
    - google-pasta=0.2.0
    - grpc-cpp=1.48.2
    - grpcio=1.48.2
    - h5py=3.11.0
    - hdf5=1.12.1
    - icc_rt=2022.1.0
    - icu=58.2
    - idna=3.7
    - importlib-metadata=7.0.1
    - intel-openmp=2023.1.0
    - jpeg=9e
    - keras=2.10.0
    - keras-preprocessing=1.1.2
    - libcurl=8.7.1
    - libpng=1.6.39
    - libprotobuf=3.20.3
    - libssh2=1.10.0
    - markdown=3.4.1
    - markupsafe=2.1.3
    - mkl=2023.1.0
    - mkl-service=2.4.0
    - mkl_fft=1.3.8
    - mkl_random=1.2.4
    - multidict=6.0.4
    - numpy=1.26.4
    - numpy-base=1.26.4
    - oauthlib=3.2.2
    - openssl=1.1.1w
    - opt_einsum=3.3.0
    - packaging=23.2
    - pip=24.0
    - pyasn1=0.4.8
    - pyasn1-modules=0.2.8
    - pybind11-abi=5
    - pycparser=2.21
    - pyjwt=2.8.0
    - pyopenssl=23.2.0
    - pysocks=1.7.1
    - python=3.9.18
    - python-flatbuffers=2.0
    - re2=2022.04.01
    - requests=2.31.0
    - requests-oauthlib=1.3.0
    - rsa=4.7.2
    - scipy=1.13.0
    - setuptools=69.5.1
    - six=1.16.0
    - snappy=1.1.10
    - sqlite=3.45.3
    - tbb=2021.8.0
    - tensorboard=2.10.0
    - tensorboard-data-server=0.6.1
    - tensorboard-plugin-wit=1.8.1
    - tensorflow=2.10.0
    - tensorflow-base=2.10.0
    - tensorflow-estimator=2.10.0
    - termcolor=2.1.0
    - typing_extensions=4.11.0
    - tzdata=2024a
    - ucrt=10.0.22621.0
    - urllib3=2.2.1
    - vc=14.2
    - vc14_runtime=14.38.33130
    - vs2015_runtime=14.38.33130
    - werkzeug=2.3.8
    - wheel=0.43.0
    - win_inet_pton=1.1.0
    - wrapt=1.14.1
    - yarl=1.9.3
    - zipp=3.17.0
    - zlib=1.2.13
    - pip:
          - libclang==18.1.1
          - protobuf==3.19.6
          - tensorflow-io-gcs-filesystem==0.31.0
